name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: setup-android
      uses: msfjarvis/setup-android@0.2
      with:
          # Gradle tasks to run - If you want to run ./gradlew assemble, specify assemble here. 
        gradleTasks: assembleDebug
